### PR TITLE
Fixing keyboard names. Fixes #523

### LINKED ISSUE #523: Incorrect Keyboard Layout Titles
@KraXen72 could you please help with this :sweat_smile: 
With the current version there are some naming issues I've found.

# 1.
I believe PTThumbKey should have the title = "PT Thumb-Key português", but it says Type-Split.
```
PTThumbKey.kt:     title = "PT Type-Split português",
PTTypeSplit.kt:    title = "PT Type-Split português",
```

# 2.
Any idea which layout FRTypeSplit.kt is? Is it french, español, or a mix of both?
```
FRTypeSplit.kt:    title = "ES Type-Split français",
ESTypeSplit.kt:    title = "ES Type-Split español",
```

# 3.
I might as well ask here. What is "EN NO Type-Split"? should its title include 'english' and the other language it is for? I'm reading "NO" as an english word and seeing "no type-split" lol.

# Images
thumbkey_layout_name1 thumbkey_layout_name2

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: app/src/main/java/com/dessalines/thumbkey/keyboards/DEThumbKey.kt [hunk 1]
```diff
@@ -468,7 +468,7 @@ val KB_DE_THUMBKEY_SHIFTED = KeyboardC(
 )
 
 val KB_DE_THUMBKEY: KeyboardDefinition = KeyboardDefinition(
-    title = "DE Thumb-Key deutch",
+    title = "deutch thumb-key",
```
Comment (KraXen72) [inline app/src/main/java/com/dessalines/thumbkey/keyboards/DEThumbKey.kt:471]: isn't it spelled "Deutsch"?

File: app/src/main/java/com/dessalines/thumbkey/keyboards/DETypeSplit.kt [hunk 2]
```diff
@@ -559,7 +559,7 @@ val KB_DE_TYPESPLIT_SHIFTED = KeyboardC(
 )
 
 val KB_DE_TYPESPLIT: KeyboardDefinition = KeyboardDefinition(
-    title = "DE Type-Split deutsch",
+    title = "deutsch type-split",
```
Comment (KraXen72) [inline app/src/main/java/com/dessalines/thumbkey/keyboards/DETypeSplit.kt:562]: tbh personally i liked the user of capital letters, it makes it easier to distinguish parts of the title than everything in small letters.

Comment (dessalines) [reply app/src/main/java/com/dessalines/thumbkey/keyboards/DETypeSplit.kt:562]: I did a few, but they did not look good, mainly because the official names of most languages do not use upper-case.

File: app/src/main/java/com/dessalines/thumbkey/keyboards/DEThumbKey.kt (hunk 1 above)
Comment (dessalines) [reply app/src/main/java/com/dessalines/thumbkey/keyboards/DEThumbKey.kt]: Fixed now.

**Comment by dessalines** [comment]
I'll merge this as its a big improvement on some of the redundant keyboard titles. Its of course up for corrections / fixes in the future.
