### PR TITLE
Fixing black-screen on startup.

### LINKED ISSUE #847: App (partially) not working on 2.6.9 or above.
### Steps to reproduce

Step 1. Install any version above 2.6.9
Step 2. Try to access the settings page/the app itself

### Expected behavior

It should work regardless of device.

### Actual behavior

It can be set as a keyboard on the OS settings, but without working settings it cannot be configured.

### version of the program

2.6.9

### Android version

Android 12, MIUI 14.0.3

### Device

Xiamo Redmi Note 9S

### Other details

This issue might be caused by the dependency upgrade that took place in 2.6.9 (#628), rendering the app un-configurable on some devices (I have yet to proof this on other devices)
The upgraded dependencies of gradle are:
com.android.application (8.2.1 -- 8.2.2)
com.android.library  (same as above)
androidx.compose.material:material-icons-extended-desktop (1.6.0 release candidate 1 -- 1.6.0)
androidx.compose.ui:ui  (same as above)
androidx.compose.runtime:runtime-livedata (same as above)
androidx.compose.ui:ui-tooling (same as above)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dessalines**
- Reworked settings to not use pointless remembers, since they're already using the DB.
- Made changelog popup and version update only occur on non-setup startup.
- Fixes #847

### CODE REVIEW

File: app/src/main/java/com/dessalines/thumbkey/MainActivity.kt [hunk 1]
```diff
@@ -68,51 +70,51 @@ class MainActivity : AppCompatActivity() {
             ThumbkeyTheme(
                 settings = settings,
             ) {
-                if (appSettingsViewModel.appSettings.isInitialized) {
```
Comment (dessalines) [inline app/src/main/java/com/dessalines/thumbkey/MainActivity.kt:71]: This was causing the error, and was the wrong way to go about making sure settings are initialized.

File: app/src/main/java/com/dessalines/thumbkey/ui/components/settings/SettingsActivity.kt [hunk 2]
```diff
@@ -95,7 +94,7 @@ fun SettingsActivity(
     val scrollState = rememberScrollState()
     var showConfirmResetDialog by remember { mutableStateOf(false) }
 
-    val layoutsState = remember { mutableStateOf(keyboardLayoutsSetFromDbIndexString(settings?.keyboardLayouts)) }
```
Comment (dessalines) [inline app/src/main/java/com/dessalines/thumbkey/ui/components/settings/SettingsActivity.kt:98]: Removing these remember was key, and was a leftover from the old settings library.

File: app/src/main/java/com/dessalines/thumbkey/ui/components/settings/behavior/BehaviorActivity.kt [hunk 3]
```diff
@@ -65,25 +65,20 @@ fun BehaviorActivity(
 
     val settings by appSettingsViewModel.appSettings.observeAsState()
 
-    var minSwipeLengthState by remember { mutableStateOf((settings?.minSwipeLength ?: DEFAULT_MIN_SWIPE_LENGTH).toFloat()) }
```
Comment (dessalines) [inline app/src/main/java/com/dessalines/thumbkey/ui/components/settings/behavior/BehaviorActivity.kt:68]: These remembers were pointless, but didn't cause any problems since the app DB was always initialized before going to these routes.
